language: node_js

sudo: required

services:
  - docker

cache:
  directories:
    - "${HOME}/.cache"
    - "${HOME}/.m2"

script:
  - ./ci/test/build.sh

after_failure:
  - PROJECT_NAME=akvo-lumen docker-compose -p akvo-flow-ci -f docker-compose-ci.yml logs

#after_success:
#  - ./ci/deploy.sh