version: "3"
services:
 postgres:
   build: postgres
   ports:
    - "5432:5432"
 flow-maps:
   build:
     context: .
     dockerfile: Dockerfile-dev
   volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
   ports:
      - "47480:47480"
      - "3000:3000"