version: "3"
services:

  keycloak:
    build: keycloak
    expose:
    - 8080

  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    hostname: zookeeper
    expose:
      - 32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka
    expose:
      - 9092
      - 29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,state.change.logger=INFO,kafka.producer.async.DefaultEventHandler=INFO"

  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    expose:
      - 8081
    volumes:
      - ./kafka-certs:/kafka-certs
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
      SCHEMA_REGISTRY_LISTENERS: "https://0.0.0.0:8081"
      SCHEMA_REGISTRY_SSL_CLIENT_AUTH: "true"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /kafka-certs/ca.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: qwerty
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /kafka-certs/schema-registry-server.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: asdfgh
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: zxcvbn

  postgres:
   build: postgres
   expose:
     - 5432

  flow-maps:
    environment:
      KAFKA_SCHEMA_REGISTRY: https://schema-registry:8081
      KAFKA_SERVERS: kafka:29092
      METADATA_MAX_AGE_MS: 500
      DATABASE_URL: "jdbc:postgresql://postgres/master_db?user=dbuser&password=dbpassword&ssl=true"
    depends_on:
      - postgres
      - kafka
    links:
      - windshaft:flow-maps-windshaft.flow-maps
    volumes:
      - ./postgres/provision:/pg-certs
      - ./kafka-certs:/kafka-certs
    expose:
      - 3000

  redis:
     image: redis:3.2.9

  windshaft:
     environment:
       - ENCRYPTION_KEY=sadfjlaskdfjlsadkfmewmewm
       - PGSSLROOTCERT=/pg-certs/server.crt
     links:
        - redis:flow-maps-redis-master.flow-maps
     volumes:
        - ./postgres/provision:/pg-certs
     expose:
       - 4000