version: "3"
services:

  keycloak:
    ports:
     - "8080:8080"

  flow-maps:
    build:
     context: backend
     dockerfile: Dockerfile-dev
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
    ports:
      - "47480:47480"
      - "3000:3000"

  redis:
     image: redis:3.2.9

  windshaft:
    build: windshaft
    environment:
      - NODE_ENV=development
      - LUMEN_ENCRYPTION_KEY=supersecret
    volumes:
       - ./windshaft/config/dev:/config
    ports:
      - "4000:4000"

  nginx:
    build:
     context: nginx
     dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/viewer:/usr/share/nginx/html/viewer
    ports:
      - "7070:80"