version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    hostname: zookeeper
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181

  postgres:
   build: postgres
   ports:
    - "5432:5432"

  flow-maps:
    image: "akvo/akvo-maps:${IMAGE_TAG}"
    environment:
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081
      KAFKA_SERVERS: kafka:29092
      DATABASE_URL: "jdbc:postgresql://postgres/a_tenant_db?user=a_tenant_user&password=a_tenant_password"
    depends_on:
      - postgres
      - kafka
    links:
      - windshaft:akvo-flow-maps-windshaft.flow-maps
    ports:
      - "3000:3000"

  redis:
     image: redis:3.2.9
  windshaft:
      image: "akvo/akvo-maps:${IMAGE_TAG}"
      environment:
       - LUMEN_ENCRYPTION_KEY=sadfjlaskdfjlsadkfmewmewm
       - PGSSLMODE=allow
     links:
        - redis:redis-master-flow-maps.flow-maps
     ports:
       - "4000:4000"

  tests:
    image: akvo-flow-dev:develop
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
    depends_on:
      - flow-maps
      - windshaft
      - postgres
    command: "true"
