apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flow-maps-redis-master
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: redis
        role: master
        client: flow-maps
        app: flow-maps
    spec:
      containers:
      - name: master
        image: redis:3.2.9
        resources:
          requests:
            cpu: "50m"
            memory: 100Mi
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: flow-maps-redis-master
  namespace: default
  labels:
    run: redis
    role: master
    client: flow-maps
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    run: redis
    role: master
    client: flow-maps